//try catch
const num1=30;
const num3=10;

console.log(num1);


try {
    console.log(num2);
} catch (error) {
    console.log(error);
}

console.log(num3);